apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arcten.fullname" . }}-backend
  labels:
    {{- include "arcten.labels" . | nindent 4 }}
    app: {{ include "arcten.fullname" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "arcten.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "arcten.fullname" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.imageCredentials.registry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ include "arcten.fullname" . }}-config
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "arcten.fullname" . }}-secrets
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "arcten.fullname" . }}-secrets
                  key: JWT_SECRET
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "arcten.fullname" . }}-secrets
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "arcten.fullname" . }}-secrets
                  key: ADMIN_PASSWORD
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
