apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcten.fullname" . }}-backend
  labels:
    {{- include "arcten.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "arcten.fullname" . }}-backend
