apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arcten.fullname" . }}-secrets
  labels:
    {{- include "arcten.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_URI: {{ .Values.secrets.mongodbUri | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  ADMIN_EMAIL: {{ .Values.secrets.adminEmail | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | b64enc | quote }}
